<?php

use Illuminate\Database\Seeder;

class CustomersTableSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        $customers = [
            [
                'id'         => '1',
                'username'   => 'rupendra',
                'first_name' => 'Rupendra',
                'last_name'  => 'Joshi',
                'email'      => 'info@radiantnepal.com',
                'company'    => 'Radiant Infotech Nepal P. Ltd.',
                'address'    => 'Kamladi',
                'phone'      => '4445765,9851016916',
                'password'   => '$2y$10$oIGIXLczde0yvjNYYEdv3.qTiH19LNAIHntYyuZeOgHoj6O59kuWe',
                'status'     => '0',
                'country'    => 'Nepal',
                'created_at' => '2015-02-07'
            ],
            [
                'id'         => '2',
                'username'   => 'ashokmjn',
                'first_name' => 'Ashok',
                'last_name'  => 'Maharjan',
                'email'      => 'ashokmjn@gmail.com',
                'company'    => 'Jamb Technologies P.Ltd.',
                'address'    => 'Kumaripati',
                'phone'      => '9841582561',
                'password'   => '6f5c71237d8a89174cb3664730d0ef29',
                'status'     => '0',
                'country'    => 'Nepal',
                'created_at' => '2015-09-24'
            ],
            [
                'id'         => '3',
                'username'   => 'ezone',
                'first_name' => 'Damodar',
                'last_name'  => 'Adhikari',
                'email'      => 'damodar@ezone.com.np',
                'company'    => 'Ezone International Pvt.Ltd.',
                'address'    => 'New Baneshwor',
                'phone'      => '9851083635',
                'password'   => '$2y$10$oIGIXLczde0yvjNYYEdv3.qTiH19LNAIHntYyuZeOgHoj6O59kuWe',
                'status'     => '0',
                'country'    => 'Nepal',
                'created_at' => '2016-05-03'
            ],
            [
                'id'         => '4',
                'username'   => 'kaymu',
                'first_name' => 'Rajeev',
                'last_name'  => 'Amatya',
                'email'      => 'rajeev.amatya@np.kaymu.com',
                'company'    => 'Kaymu Nepal',
                'address'    => 'Naxal',
                'phone'      => '9801292910',
                'password'   => '$2y$10$oIGIXLczde0yvjNYYEdv3.qTiH19LNAIHntYyuZeOgHoj6O59kuWe',
                'status'     => '0',
                'country'    => 'Nepal',
                'created_at' => '2015-11-18'
            ],
            [
                'id'         => '5',
                'username'   => 'unicef_nepal',
                'first_name' => 'Raju',
                'last_name'  => 'Maharjan',
                'email'      => 'rmaharjan@unicef.org',
                'company'    => 'UNICEF Nepal',
                'address'    => 'Patan',
                'phone'      => '',
                'password'   => '4330129d2ef7a19f2c807e91acbdbb9a',
                'status'     => '0',
                'country'    => 'Nepal',
                'created_at' => '2015-07-22'
            ],
            [
                'id'         => '6',
                'username'   => 'sunshine',
                'first_name' => 'Saroj',
                'last_name'  => '',
                'email'      => 'nagarkotsunshine@gmail.com',
                'company'    => 'Hotel Sunshine ',
                'address'    => 'Nagarkot',
                'phone'      => '6680105,9841109461',
                'password'   => '$2y$10$oIGIXLczde0yvjNYYEdv3.qTiH19LNAIHntYyuZeOgHoj6O59kuWe',
                'status'     => '0',
                'country'    => 'Nepal',
                'created_at' => '2015-10-18'
            ],
            [
                'id'         => '7',
                'username'   => 'samrachana',
                'first_name' => 'Samrachana',
                'last_name'  => 'Shakya',
                'email'      => 'samrachana@ahrcdf.org.np',
                'company'    => 'AHRCDF',
                'address'    => '',
                'phone'      => '9841267744',
                'password'   => '$2y$10$oIGIXLczde0yvjNYYEdv3.qTiH19LNAIHntYyuZeOgHoj6O59kuWe',
                'status'     => '0',
                'country'    => 'Nepal',
                'created_at' => '2015-12-08'
            ],
            [
                'id'         => '8',
                'username'   => 'bijay_raut',
                'first_name' => 'Bijay',
                'last_name'  => 'Raut',
                'email'      => 'bijay.raut@icn.com.np',
                'company'    => 'Improvement Co. Nepal (ICN)',
                'address'    => 'Sanepa',
                'phone'      => '5533609,9818713476',
                'password'   => '$2y$10$oIGIXLczde0yvjNYYEdv3.qTiH19LNAIHntYyuZeOgHoj6O59kuWe',
                'status'     => '0',
                'country'    => 'Nepal',
                'created_at' => '2015-08-14'
            ],
            [
                'id'         => '9',
                'username'   => 'younginnovation',
                'first_name' => 'Santosh',
                'last_name'  => 'Neupane',
                'email'      => 'santosh.neupane@yipl.com.np',
                'company'    => 'Young Innovations P. Ltd.',
                'address'    => 'Kathmandu',
                'phone'      => '9841852889',
                'password'   => '$2y$10$oIGIXLczde0yvjNYYEdv3.qTiH19LNAIHntYyuZeOgHoj6O59kuWe',
                'status'     => '0',
                'country'    => 'Nepal',
                'created_at' => '2015-08-31'
            ],
            [
                'id'         => '10',
                'username'   => 'neps',
                'first_name' => 'Keshab',
                'last_name'  => 'Maharajan',
                'email'      => 'keshab.maharjan@neps.com.np',
                'company'    => 'Nepal Electronic Payment Systems Ltd.',
                'address'    => 'Naxal',
                'phone'      => '4411687',
                'password'   => 'a21cf9b21d85a0e9ad42e842f5cde4d6',
                'status'     => '0',
                'country'    => 'Nepal',
                'created_at' => '2015-09-13'
            ],
            [
                'id'         => '11',
                'username'   => 'shubha',
                'first_name' => 'Vinod',
                'last_name'  => 'Bhandari',
                'email'      => 'vinod@shubhatech.com.np',
                'company'    => 'Shubha Tech P. Ltd.',
                'address'    => 'Dillibazar',
                'phone'      => '9802024051',
                'password'   => '$2y$10$oIGIXLczde0yvjNYYEdv3.qTiH19LNAIHntYyuZeOgHoj6O59kuWe',
                'status'     => '0',
                'country'    => 'Nepal',
                'created_at' => '2015-09-13'
            ],
            [
                'id'         => '12',
                'username'   => 'raazan',
                'first_name' => 'Rajan',
                'last_name'  => 'Bhattarai',
                'email'      => 'raazan.bhattarai@gmail.com',
                'company'    => 'Farming & Agriculture Resources Management',
                'address'    => 'Kathmandu',
                'phone'      => '9841567626',
                'password'   => '$2y$10$oIGIXLczde0yvjNYYEdv3.qTiH19LNAIHntYyuZeOgHoj6O59kuWe',
                'status'     => '0',
                'country'    => 'Nepal',
                'created_at' => '2015-09-15'
            ],
            [
                'id'         => '13',
                'username'   => 'umesh',
                'first_name' => 'Umesh',
                'last_name'  => 'K.Raghubanshi',
                'email'      => 'umesh@infodev.com.np',
                'company'    => 'Infodevelopers P.Ltd.',
                'address'    => 'Sanepa',
                'phone'      => '5546470,9851068982',
                'password'   => '$2y$10$2K.NT1Xz3c6uN/otHZevN.WMvh423jzddtJ4roNAE53LBg2KMygsO',
                'status'     => '1',
                'country'    => 'Nepal',
                'created_at' => '2015-09-21'
            ],
            [
                'id'         => '14',
                'username'   => 'rhonda',
                'first_name' => 'Rhonda',
                'last_name'  => 'Eggleston',
                'email'      => 'reggleston@electronicbusinesservices.com',
                'company'    => 'Electronic Business Services ',
                'address'    => '2636 Fulton Ave Sacramento CA 95821',
                'phone'      => '19167566334',
                'password'   => 'b22383e3f54bb0065213d0d05a0266d6',
                'status'     => '0',
                'country'    => 'United States',
                'created_at' => '2015-10-28'
            ],
            [
                'id'         => '15',
                'username'   => 'rughimire',
                'first_name' => 'Rupak',
                'last_name'  => 'Raj Ghimire',
                'email'      => 'rughimire@gmail.com',
                'company'    => 'Uniaxial Software ',
                'address'    => 'Anamnagar',
                'phone'      => '9841046796',
                'password'   => '$2y$10$vJJt9zG8fjSBDDrN5zKBnuK.cFelEDW35anh3N90MQd4EFsHMA1x6',
                'status'     => '1',
                'country'    => 'Nepal',
                'created_at' => '2015-06-11'
            ],
            [
                'id'         => '16',
                'username'   => 'ishan',
                'first_name' => 'Ishan',
                'last_name'  => 'Gauli',
                'email'      => 'gauli.ishan@gmail.com',
                'company'    => 'Rato Bangala School',
                'address'    => 'Patan Dhoka',
                'phone'      => '9860810151',
                'password'   => '1309c03689fa15ef5a91a30cdc599991',
                'status'     => '0',
                'country'    => 'Nepal',
                'created_at' => '2015-06-11'
            ],
            [
                'id'         => '17',
                'username'   => 'surajshrestha',
                'first_name' => 'Suraj',
                'last_name'  => 'Shrestha',
                'email'      => 'suraj.s@ptas.com.np',
                'company'    => 'Pathway Technologies & Services P. Ltd.',
                'address'    => 'Thapathali',
                'phone'      => '4101544,9851052800',
                'password'   => '$2y$10$D3G3IuVLF4Ys1tFxbjp4hOFNFUwt.gOe/osfYbQ/0CW4VBhC0FG9G',
                'status'     => '1',
                'country'    => 'Nepal',
                'created_at' => '2015-11-15'
            ],
            [
                'id'         => '18',
                'username'   => 'today_khabar',
                'first_name' => 'Rabindra',
                'last_name'  => 'Yadav',
                'email'      => 'webrabin@gmail.com',
                'company'    => 'TodayKhabar',
                'address'    => 'Kathmandu',
                'phone'      => '9851033634,9840070083',
                'password'   => '$2y$10$oIGIXLczde0yvjNYYEdv3.qTiH19LNAIHntYyuZeOgHoj6O59kuWe',
                'status'     => '0',
                'country'    => 'Nepal',
                'created_at' => '2015-11-30'
            ],
            [
                'id'         => '19',
                'username'   => 'bijesh',
                'first_name' => 'Bijesh',
                'last_name'  => 'Bania',
                'email'      => 'bijesh.bania@asoent.com',
                'company'    => 'Associated Enterprises (AE International)',
                'address'    => 'Putalisadak',
                'phone'      => '4248930,9851063194',
                'password'   => '$2y$10$oIGIXLczde0yvjNYYEdv3.qTiH19LNAIHntYyuZeOgHoj6O59kuWe',
                'status'     => '0',
                'country'    => 'Nepal',
                'created_at' => '2015-11-12'
            ],
            [
                'id'         => '20',
                'username'   => 'taranga',
                'first_name' => 'Shankar',
                'last_name'  => 'Pokharel',
                'email'      => 'shankar@taranga.com.np',
                'company'    => 'Maulik Tarang P. Ltd.',
                'address'    => 'Maharajgunj',
                'phone'      => '9851210480',
                'password'   => '$2y$10$oIGIXLczde0yvjNYYEdv3.qTiH19LNAIHntYyuZeOgHoj6O59kuWe',
                'status'     => '0',
                'country'    => 'Nepal',
                'created_at' => '2016-07-02'
            ],
            [
                'id'         => '21',
                'username'   => 'bhupendra',
                'first_name' => 'Bhupendra',
                'last_name'  => 'Bista',
                'email'      => 'bhupendra.bista@ctznbank.com',
                'company'    => 'Citizens Bank Intl\' Ltd.',
                'address'    => 'Kamladi',
                'phone'      => '',
                'password'   => '$2y$10$oIGIXLczde0yvjNYYEdv3.qTiH19LNAIHntYyuZeOgHoj6O59kuWe',
                'status'     => '0',
                'country'    => 'Nepal',
                'created_at' => '2016-02-21'
            ],
            [
                'id'         => '22',
                'username'   => 'sureshverma',
                'first_name' => 'Suresh',
                'last_name'  => 'Verma',
                'email'      => 'suresh.verma@3iconsulting.in',
                'company'    => '3i Consulting Pvt. Ltd',
                'address'    => 'Noida',
                'phone'      => '917289095272',
                'password'   => 'c7be16d1b16ed822672a064a686a9de7',
                'status'     => '0',
                'country'    => 'India',
                'created_at' => '2016-02-18'
            ],
            [
                'id'         => '23',
                'username'   => 'sudeep',
                'first_name' => 'Sudeep',
                'last_name'  => 'Shrestha',
                'email'      => 'sudeep@syntegrate.com.np',
                'company'    => 'Syntegrate',
                'address'    => 'Chundevi',
                'phone'      => '4720329,4720304 ',
                'password'   => '$2y$10$oIGIXLczde0yvjNYYEdv3.qTiH19LNAIHntYyuZeOgHoj6O59kuWe',
                'status'     => '0',
                'country'    => 'Nepal',
                'created_at' => '2016-04-03'
            ],
            [
                'id'         => '24',
                'username'   => 'woori',
                'first_name' => 'Dipendra',
                'last_name'  => 'Shrestha',
                'email'      => 'info@ncloud.com.np',
                'company'    => 'nCloud Pvt. Ltd.',
                'address'    => 'Teku',
                'phone'      => '4100107,9801107937',
                'password'   => '$2y$10$bAQWq3EMAAH/aCth6MSySe21krZCOU4LcKdQ/iXqIQkUVP1GsFCBO',
                'status'     => '1',
                'country'    => 'Nepal',
                'created_at' => '2016-03-18'
            ],
            [
                'id'         => '25',
                'username'   => 'iwebnepal',
                'first_name' => 'Roshan',
                'last_name'  => 'Konda',
                'email'      => 'info@iwebnepal.com',
                'company'    => 'I.Web Nepal Pvt Ltd.',
                'address'    => 'Maitidevi',
                'phone'      => '4417952,9803167159',
                'password'   => '$2y$10$/dL41JF6Dl0t623C0Q1HdOJ9xmX89G3v4RTYtog2.j6Wy2tebUC1W',
                'status'     => '1',
                'country'    => 'Nepal',
                'created_at' => '2016-03-24'
            ],
            [
                'id'         => '26',
                'username'   => 'gyanss',
                'first_name' => 'Ajit',
                'last_name'  => 'Sigdel',
                'email'      => 'info@gyansagar.com.np',
                'company'    => 'Gyan Sagar Services P. Ltd.',
                'address'    => 'Chahabil',
                'phone'      => '4811888',
                'password'   => '$2y$10$oIGIXLczde0yvjNYYEdv3.qTiH19LNAIHntYyuZeOgHoj6O59kuWe',
                'status'     => '0',
                'country'    => 'Nepal',
                'created_at' => '2016-03-27'
            ],
            [
                'id'         => '27',
                'username'   => 'robin',
                'first_name' => 'Robin',
                'last_name'  => 'Sharma',
                'email'      => 'onlinekinmel@gmail.com',
                'company'    => 'Online Kinmel',
                'address'    => 'Kupondole',
                'phone'      => '9801001892',
                'password'   => 'e3b03bda34847ec7fb53550e749b473c',
                'status'     => '0',
                'country'    => 'Nepal',
                'created_at' => '2016-03-28'
            ],
            [
                'id'         => '28',
                'username'   => 'longtail',
                'first_name' => 'Bipin',
                'last_name'  => 'Bajracharya',
                'email'      => 'bipin@longtail.info',
                'company'    => 'Longtail e- media ',
                'address'    => 'Patandhoka',
                'phone'      => '9851092983',
                'password'   => '7d9a589241ac193af39fd073cf501577',
                'status'     => '0',
                'country'    => 'Nepal',
                'created_at' => '2016-04-04'
            ],
            [
                'id'         => '29',
                'username'   => 'creationsoft',
                'first_name' => 'Shiva',
                'last_name'  => 'Khanal',
                'email'      => 'info@creationsoftnepal.com',
                'company'    => 'Creation Soft Nepal Pvt. Ltd.',
                'address'    => 'Banasthali',
                'phone'      => '4350572,9841219864',
                'password'   => '$2y$10$EtQZleNaj9bBFweSbbyAnuB1G5U0JtLCLhDrPQOT/6ZVlGL6x1OkO',
                'status'     => '1',
                'country'    => 'Nepal',
                'created_at' => '2016-04-10'
            ],
            [
                'id'         => '30',
                'username'   => 'geospatial',
                'first_name' => 'Diwakar',
                'last_name'  => 'Maharjan',
                'email'      => 'system@geosp.com',
                'company'    => 'GeoSpatial Systems Pvt. Ltd.',
                'address'    => 'Jawalakhel',
                'phone'      => '5531131,9803048051',
                'password'   => '5fd12ab367e6e7170d9d214c285e1191',
                'status'     => '0',
                'country'    => 'Nepal',
                'created_at' => '2016-04-21'
            ],
            [
                'id'         => '31',
                'username'   => 'kapeel',
                'first_name' => 'Kapil',
                'last_name'  => 'Dahal',
                'email'      => 'kapeel4@gmail.com',
                'company'    => 'Techware Pvt. Ltd.',
                'address'    => 'Balkumari',
                'phone'      => '9851196943,9849220335',
                'password'   => '$2y$10$oIGIXLczde0yvjNYYEdv3.qTiH19LNAIHntYyuZeOgHoj6O59kuWe',
                'status'     => '0',
                'country'    => 'Nepal',
                'created_at' => '2016-04-24'
            ],
            [
                'id'         => '32',
                'username'   => 'shambhu',
                'first_name' => 'Shambhu',
                'last_name'  => 'Pahadi',
                'email'      => 'shambhu.pahadi@himalayantelecom.com',
                'company'    => 'Himalayan Telecom International Pvt. Ltd.',
                'address'    => 'Uttar Dhoka, Lazimpat',
                'phone'      => '4001114,9851153111',
                'password'   => '$2y$10$oIGIXLczde0yvjNYYEdv3.qTiH19LNAIHntYyuZeOgHoj6O59kuWe',
                'status'     => '0',
                'country'    => 'Nepal',
                'created_at' => '2016-04-25'
            ],
            [
                'id'         => '33',
                'username'   => 'rama',
                'first_name' => 'Rama',
                'last_name'  => 'Kharel',
                'email'      => 'info@ezone.com.np',
                'company'    => 'e-Zone International Pvt. Ltd.',
                'address'    => 'New Baneshwor',
                'phone'      => '4483088',
                'password'   => '$2y$10$3qmpw4zUWWrXHYoTS2.2/ebNnNKR57Tg4Y5iyLK6ITZBYLs9QBl1C',
                'status'     => '1',
                'country'    => 'Nepal',
                'created_at' => '2016-05-03'
            ],
            [
                'id'         => '34',
                'username'   => 'jason',
                'first_name' => 'Jason',
                'last_name'  => 'Thatcher',
                'email'      => 'jthatcher@themediatrust.com',
                'company'    => 'themediatrust .com',
                'address'    => 'US',
                'phone'      => '703-317-7822,703-893-0325',
                'password'   => '030bda040ca4652e479ffdd5d37ced3d',
                'status'     => '0',
                'country'    => 'United States',
                'created_at' => '2016-05-04'
            ],
            [
                'id'         => '35',
                'username'   => 'himali',
                'first_name' => 'Gyaneshwor',
                'last_name'  => 'Karki',
                'email'      => 'info@mountdigit.com',
                'company'    => 'Mount Digit Technology P.Ltd.',
                'address'    => 'Dhobighat',
                'phone'      => '5522539',
                'password'   => '82421c94ef1c7f51122094d1d7a98d2d',
                'status'     => '0',
                'country'    => 'Nepal',
                'created_at' => '2016-05-06'
            ],
            [
                'id'         => '36',
                'username'   => 'asteriskt',
                'first_name' => 'Sandeep',
                'last_name'  => 'Jalan',
                'email'      => 'sandeepjalan07@gmail.com',
                'company'    => 'Asterisk Technology P.Ltd.',
                'address'    => 'Tripureshwor',
                'phone'      => '9851116164',
                'password'   => '86adcbdcb53211c5a0f495c797437e03',
                'status'     => '0',
                'country'    => 'Nepal',
                'created_at' => '2016-05-09'
            ],
            [
                'id'         => '37',
                'username'   => 'jhakkas',
                'first_name' => 'Rajan',
                'last_name'  => 'Pant',
                'email'      => 'rajanpant@outlook.com',
                'company'    => 'Jhakkas Solutions ',
                'address'    => 'Manbhawan ,Jawalakhel',
                'phone'      => '9851040042',
                'password'   => '$2y$10$oIGIXLczde0yvjNYYEdv3.qTiH19LNAIHntYyuZeOgHoj6O59kuWe',
                'status'     => '0',
                'country'    => 'Nepal',
                'created_at' => '2016-05-10'
            ],
            [
                'id'         => '38',
                'username'   => 'medep',
                'first_name' => 'Ramji',
                'last_name'  => 'Neupane',
                'email'      => 'info@medep.org.np',
                'company'    => 'Micro Enterprise Development Programme (MDEP)',
                'address'    => 'Dhobighat',
                'phone'      => '5541949',
                'password'   => '$2y$10$oIGIXLczde0yvjNYYEdv3.qTiH19LNAIHntYyuZeOgHoj6O59kuWe',
                'status'     => '0',
                'country'    => 'Nepal',
                'created_at' => '2016-05-10'
            ],
            [
                'id'         => '39',
                'username'   => 'vianet',
                'first_name' => 'Anup',
                'last_name'  => 'Lal Manandhar',
                'email'      => 'anup@vianet.com.np',
                'company'    => 'Vianet Communications P.Ltd.',
                'address'    => 'Jawalakhel',
                'phone'      => '9801194914,9851049431',
                'password'   => '$2y$10$oIGIXLczde0yvjNYYEdv3.qTiH19LNAIHntYyuZeOgHoj6O59kuWe',
                'status'     => '0',
                'country'    => 'Nepal',
                'created_at' => '2016-05-11'
            ],
            [
                'id'         => '40',
                'username'   => 'peter',
                'first_name' => 'Peter',
                'last_name'  => 'Satrapa-Binder',
                'email'      => 'peter@visualweb.co.th',
                'company'    => 'Visual Web Co. Ltd. ',
                'address'    => 'Thailand',
                'phone'      => '',
                'password'   => '9b23cc8c171e10499eeb0c65f3092704',
                'status'     => '0',
                'country'    => 'Thailand',
                'created_at' => '2016-05-12'
            ],
            [
                'id'         => '41',
                'username'   => 'mhl',
                'first_name' => 'Surendra',
                'last_name'  => 'Serchan',
                'email'      => 'mentalhospitallagankhel@gmail.com',
                'company'    => 'Mental Hospital',
                'address'    => 'Lagankhel',
                'phone'      => '5521333',
                'password'   => '$2y$10$oIGIXLczde0yvjNYYEdv3.qTiH19LNAIHntYyuZeOgHoj6O59kuWe',
                'status'     => '0',
                'country'    => 'Nepal',
                'created_at' => '2016-05-15'
            ],
            [
                'id'         => '42',
                'username'   => 'pankaj',
                'first_name' => 'Pankaj',
                'last_name'  => 'Bhattarai',
                'email'      => 'bhattaraipankaz@gmail.com',
                'company'    => 'Health Advancement Program in South Asia (HAPSA)',
                'address'    => 'Buddha Nagar',
                'phone'      => '9841140403',
                'password'   => '80ae35797a18a7b236798d5f963715e8',
                'status'     => '0',
                'country'    => 'Nepal',
                'created_at' => '2016-05-17'
            ],
            [
                'id'         => '43',
                'username'   => 'anup',
                'first_name' => 'Anup',
                'last_name'  => 'Acharya',
                'email'      => 'anup.acharya@gmail.com',
                'company'    => 'RamroJob Pvt. Ltd.',
                'address'    => 'Dillibazar',
                'phone'      => '4416311,9851098933',
                'password'   => '$2y$10$tE0d6n7zMIIhAO.eiVZHbu2lzhoC5g4EujlxqPRDa0jQ6hS5AhNfq',
                'status'     => '1',
                'country'    => 'Nepal',
                'created_at' => '2016-05-17'
            ],
            [
                'id'         => '44',
                'username'   => 'sastra',
                'first_name' => 'Pramod',
                'last_name'  => 'Shrestha',
                'email'      => 'info@sastranetwork.com',
                'company'    => 'Sastra Network Solution',
                'address'    => 'Putalisadak',
                'phone'      => '4242523,4242967',
                'password'   => '$2y$10$oIGIXLczde0yvjNYYEdv3.qTiH19LNAIHntYyuZeOgHoj6O59kuWe',
                'status'     => '0',
                'country'    => 'Nepal',
                'created_at' => '2016-05-20'
            ],
            [
                'id'         => '45',
                'username'   => 'luniva01',
                'first_name' => 'Nurendra',
                'last_name'  => 'Shakya',
                'email'      => 'nhurenshakya@gmail.com',
                'company'    => 'Luniva Tech P.Ltd.',
                'address'    => 'Putalisadak',
                'phone'      => '9851220207',
                'password'   => 'a7389e9d075e19054d921f331df3791b',
                'status'     => '0',
                'country'    => 'Nepal',
                'created_at' => '2016-06-01'
            ],
            [
                'id'         => '46',
                'username'   => 'rupesh',
                'first_name' => 'Rupesh',
                'last_name'  => 'Adhikari',
                'email'      => 'rupesh@greenhillcity.com',
                'company'    => 'Greenhill City Pvt.Ltd.',
                'address'    => 'Imadol',
                'phone'      => '9801242029',
                'password'   => '$2y$10$oIGIXLczde0yvjNYYEdv3.qTiH19LNAIHntYyuZeOgHoj6O59kuWe',
                'status'     => '0',
                'country'    => 'Nepal',
                'created_at' => '2016-06-02'
            ],
            [
                'id'         => '47',
                'username'   => 'kumarijob',
                'first_name' => 'Sandesh',
                'last_name'  => 'Bhandari',
                'email'      => 'sandesh@kumarijob.com',
                'company'    => 'Kumari Job ',
                'address'    => 'Baneshwor',
                'phone'      => '4478845',
                'password'   => '$2y$10$oIGIXLczde0yvjNYYEdv3.qTiH19LNAIHntYyuZeOgHoj6O59kuWe',
                'status'     => '0',
                'country'    => 'Nepal',
                'created_at' => '2016-06-16'
            ],
            [
                'id'         => '48',
                'username'   => 'rajiv',
                'first_name' => 'Rajiv',
                'last_name'  => 'Karna',
                'email'      => 'rajiv@exclusiveminds.com',
                'company'    => 'XclusiveMINDS Pvt. Ltd.',
                'address'    => 'Anamnagar',
                'phone'      => '4262682,9851089243',
                'password'   => '$2y$10$oIGIXLczde0yvjNYYEdv3.qTiH19LNAIHntYyuZeOgHoj6O59kuWe',
                'status'     => '0',
                'country'    => 'Nepal',
                'created_at' => '2016-06-20'
            ],
            [
                'id'         => '49',
                'username'   => 'santosh',
                'first_name' => 'Santosh',
                'last_name'  => 'Sunuwar',
                'email'      => 'info@ganeshdeeppashmina.com',
                'company'    => 'GaneshDeep Pashmina Udhyog',
                'address'    => 'Kalanki',
                'phone'      => '4280956,4274833',
                'password'   => '$2y$10$oIGIXLczde0yvjNYYEdv3.qTiH19LNAIHntYyuZeOgHoj6O59kuWe',
                'status'     => '0',
                'country'    => 'Nepal',
                'created_at' => '2016-06-22'
            ],
            [
                'id'         => '50',
                'username'   => 'navin',
                'first_name' => 'Navin',
                'last_name'  => 'Bhansali',
                'email'      => 'navin@airtech.com.np',
                'company'    => 'Airtech Industries P.Ltd.',
                'address'    => 'Thapathali',
                'phone'      => '4219999,9801034288',
                'password'   => '$2y$10$oIGIXLczde0yvjNYYEdv3.qTiH19LNAIHntYyuZeOgHoj6O59kuWe',
                'status'     => '0',
                'country'    => 'Nepal',
                'created_at' => '2016-06-22'
            ],
            [
                'id'         => '51',
                'username'   => 'kozzaja',
                'first_name' => 'Kishan',
                'last_name'  => 'Poudel',
                'email'      => 'kishan@kozzaja.com',
                'company'    => 'Kozzaja Infotech P. Ltd.',
                'address'    => 'New Baneshwor',
                'phone'      => '9851220365',
                'password'   => '$2y$10$A5dj4EkWGYmcNEXR4a0um.TEP2JEFrH7jEfjPIUt5MjFE5oRiqRqm',
                'status'     => '1',
                'country'    => 'Nepal',
                'created_at' => '2016-06-28'
            ],
            [
                'id'         => '52',
                'username'   => 'prashant',
                'first_name' => 'Prashant',
                'last_name'  => 'Gurung',
                'email'      => 'prashant@muncha.com',
                'company'    => 'Muncha.com',
                'address'    => 'Ekantakune',
                'phone'      => '5000737,9856027232',
                'password'   => '25106ad0bc09da66912b7aa2287495a1',
                'status'     => '0',
                'country'    => 'Nepal',
                'created_at' => '2016-06-29'
            ],
            [
                'id'         => '53',
                'username'   => 'sailesh',
                'first_name' => 'Sailesh',
                'last_name'  => '',
                'email'      => 'sailesh@megatech.com.np',
                'company'    => 'Megatech',
                'address'    => 'Hattisar',
                'phone'      => '4233900',
                'password'   => '$2y$10$oIGIXLczde0yvjNYYEdv3.qTiH19LNAIHntYyuZeOgHoj6O59kuWe',
                'status'     => '0',
                'country'    => 'Nepal',
                'created_at' => '2016-06-29'
            ],
            [
                'id'         => '54',
                'username'   => 'brihat123',
                'first_name' => 'Pranish',
                'last_name'  => 'Balami',
                'email'      => 'pranish@brihatinvestments.com',
                'company'    => 'Brihat Investments Pvt. Ltd.',
                'address'    => 'Teku',
                'phone'      => '4104603,4104602',
                'password'   => '$2y$10$oIGIXLczde0yvjNYYEdv3.qTiH19LNAIHntYyuZeOgHoj6O59kuWe',
                'status'     => '0',
                'country'    => 'Nepal',
                'created_at' => '2016-07-22'
            ],
            [
                'id'         => '55',
                'username'   => 'psoft',
                'first_name' => 'Naresh',
                'last_name'  => 'Purbey',
                'email'      => 'npurbey@ntc.net.np',
                'company'    => 'Purbey Software Pvt. Ltd.',
                'address'    => 'Chahabil',
                'phone'      => '9851016455',
                'password'   => '$2y$10$oIGIXLczde0yvjNYYEdv3.qTiH19LNAIHntYyuZeOgHoj6O59kuWe',
                'status'     => '0',
                'country'    => 'Nepal',
                'created_at' => '2016-07-08'
            ],
            [
                'id'         => '56',
                'username'   => 'gems',
                'first_name' => 'Ramesh',
                'last_name'  => 'Maharjan',
                'email'      => 'ramesh@gems.edu.np',
                'company'    => 'GEMS',
                'address'    => 'Dhapakhel',
                'phone'      => '5003060,5521032',
                'password'   => '$2y$10$oIGIXLczde0yvjNYYEdv3.qTiH19LNAIHntYyuZeOgHoj6O59kuWe',
                'status'     => '0',
                'country'    => 'Nepal',
                'created_at' => '2016-07-14'
            ],
            [
                'id'         => '57',
                'username'   => 'setogurans',
                'first_name' => 'Basanti',
                'last_name'  => 'Timalsina',
                'email'      => 'setogurans@gmail.com',
                'company'    => 'Seto Gurans National Child Development Services',
                'address'    => 'Jhamsikhel',
                'phone'      => '9841342249',
                'password'   => '$2y$10$oIGIXLczde0yvjNYYEdv3.qTiH19LNAIHntYyuZeOgHoj6O59kuWe',
                'status'     => '0',
                'country'    => 'Nepal',
                'created_at' => '2016-07-18'
            ],
            [
                'id'         => '58',
                'username'   => 'npn47',
                'first_name' => 'Jorge',
                'last_name'  => 'Van Der Wilk',
                'email'      => 'jvdwilk@npn.com.np',
                'company'    => 'Networking Professionals of Nepal Pvt. Ltd.',
                'address'    => 'Jorpati',
                'phone'      => '4910010,6203678',
                'password'   => '$2y$10$oIGIXLczde0yvjNYYEdv3.qTiH19LNAIHntYyuZeOgHoj6O59kuWe',
                'status'     => '0',
                'country'    => 'Nepal',
                'created_at' => '2016-07-21'
            ],
            [
                'id'         => '59',
                'username'   => 'synergyfinance',
                'first_name' => 'Raju',
                'last_name'  => 'Maharjan',
                'email'      => 'raju@synergyfinance.com.np',
                'company'    => 'Synergy Finance Ltd.',
                'address'    => 'Kamladi',
                'phone'      => '',
                'password'   => '$2y$10$oIGIXLczde0yvjNYYEdv3.qTiH19LNAIHntYyuZeOgHoj6O59kuWe',
                'status'     => '0',
                'country'    => 'Nepal',
                'created_at' => '2016-07-22'
            ],
            [
                'id'         => '60',
                'username'   => 'dev',
                'first_name' => 'Dev',
                'last_name'  => 'Khadka',
                'email'      => 'dev.khadka@syntechnepal.com',
                'company'    => 'Synergy Tech Software P. Ltd.',
                'address'    => 'Pulchowk',
                'phone'      => '5009087,9841358015',
                'password'   => 'ed1c8a912a1f65d3ce3c75065f17d85f',
                'status'     => '0',
                'country'    => 'Nepal',
                'created_at' => '2016-07-24'
            ],
            [
                'id'         => '61',
                'username'   => 'maheshwor',
                'first_name' => 'Maheshwor',
                'last_name'  => 'Maharjan',
                'email'      => 'maheswor@gmail.com',
                'company'    => 'Info Nepal -Data Research And Analysis Center Pvt. Ltd.',
                'address'    => 'Patandhoka',
                'phone'      => '5533950,9851174737',
                'password'   => '$2y$10$oIGIXLczde0yvjNYYEdv3.qTiH19LNAIHntYyuZeOgHoj6O59kuWe',
                'status'     => '0',
                'country'    => 'Nepal',
                'created_at' => '2016-07-26'
            ],
            [
                'id'         => '62',
                'username'   => 'cgroup',
                'first_name' => 'Bijay',
                'last_name'  => 'Shakya',
                'email'      => 'info@chaudharygroup.com',
                'company'    => 'Chaudhary Group',
                'address'    => 'Sanepa',
                'phone'      => '',
                'password'   => '$2y$10$oIGIXLczde0yvjNYYEdv3.qTiH19LNAIHntYyuZeOgHoj6O59kuWe',
                'status'     => '0',
                'country'    => 'Nepal',
                'created_at' => '2016-07-26'
            ],
            [
                'id'         => '63',
                'username'   => 'salin',
                'first_name' => 'Salin',
                'last_name'  => 'Shakya',
                'email'      => 'skysalin@gmail.com',
                'company'    => 'Salin',
                'address'    => 'Lalitpur',
                'phone'      => '',
                'password'   => '$2y$10$oIGIXLczde0yvjNYYEdv3.qTiH19LNAIHntYyuZeOgHoj6O59kuWe',
                'status'     => '0',
                'country'    => 'Nepal',
                'created_at' => '2016-07-27'
            ],
            [
                'id'         => '64',
                'username'   => 'sanjay',
                'first_name' => 'Sanjay',
                'last_name'  => 'K Barakoti',
                'email'      => 'sunbi.design@gmail.com',
                'company'    => 'SunBi Design Studio',
                'address'    => 'New Baneshwor',
                'phone'      => '4620354',
                'password'   => '$2y$10$oIGIXLczde0yvjNYYEdv3.qTiH19LNAIHntYyuZeOgHoj6O59kuWe',
                'status'     => '0',
                'country'    => 'Nepal',
                'created_at' => '2016-07-29'
            ],
            [
                'id'         => '65',
                'username'   => 'easytech',
                'first_name' => 'Kishan',
                'last_name'  => 'Bhari',
                'email'      => 'kishan@easytech.com.np',
                'company'    => 'Easytech Solutions Pvt. Ltd.',
                'address'    => 'Putalisadak',
                'phone'      => '4012599,9851130472',
                'password'   => '$2y$10$oIGIXLczde0yvjNYYEdv3.qTiH19LNAIHntYyuZeOgHoj6O59kuWe',
                'status'     => '0',
                'country'    => 'Nepal',
                'created_at' => '2016-08-03'
            ],
            [
                'id'         => '66',
                'username'   => 'umeshsimkhada',
                'first_name' => 'Umesh',
                'last_name'  => 'Simkhada',
                'email'      => 'umesh@markline.com.np',
                'company'    => 'Data Art Pvt. Ltd.',
                'address'    => 'Kathmandu',
                'phone'      => '9801900011',
                'password'   => '$2y$10$wwsUoV5M8Rpii9a0pO1Bb.Q0O1ok3zHwMG6jbaoQ17GmDQdgXVfpO',
                'status'     => '1',
                'country'    => 'Nepal',
                'created_at' => '2016-08-04'
            ],
            [
                'id'         => '67',
                'username'   => 'bijay_barakoti',
                'first_name' => 'Bijay',
                'last_name'  => 'Barakoti',
                'email'      => 'sunbi.bijay@gmail.com',
                'company'    => 'Naya Shakti Party Nepal',
                'address'    => 'Kathmandu',
                'phone'      => '4620354',
                'password'   => '$2y$10$oIGIXLczde0yvjNYYEdv3.qTiH19LNAIHntYyuZeOgHoj6O59kuWe',
                'status'     => '0',
                'country'    => 'Nepal',
                'created_at' => '2016-08-04'
            ],
            [
                'id'         => '68',
                'username'   => 'ioelaxman',
                'first_name' => 'Laxman',
                'last_name'  => 'Siwakoti',
                'email'      => 'ioelaxman@gmail.com',
                'company'    => 'Laxman Siwakoti',
                'address'    => 'Kathmandu',
                'phone'      => '9843786657',
                'password'   => '$2y$10$r4IRSVGVpXoLsYbElA9QSucvP46fzm5oKTOnPRToXzGIC8N7f.8eK',
                'status'     => '1',
                'country'    => 'Nepal',
                'created_at' => '2016-08-09'
            ],
            [
                'id'         => '69',
                'username'   => 'innovative',
                'first_name' => 'Bhushan',
                'last_name'  => 'Raj Shrestha',
                'email'      => 'sbhusan@mail.com.np',
                'company'    => 'Innovative Solution Pvt. Ltd.',
                'address'    => 'Chakupat',
                'phone'      => '9851082139',
                'password'   => '$2y$10$oIGIXLczde0yvjNYYEdv3.qTiH19LNAIHntYyuZeOgHoj6O59kuWe',
                'status'     => '0',
                'country'    => 'Nepal',
                'created_at' => '2016-08-11'
            ],
            [
                'id'         => '70',
                'username'   => 'endonepal',
                'first_name' => 'Sudin',
                'last_name'  => 'Pradhan',
                'email'      => 'nepalendo@gmail.com',
                'company'    => 'ENDO Nepal',
                'address'    => 'Patan',
                'phone'      => '',
                'password'   => '$2y$10$j3qUdk96xSPkuYQqkpMf1uImbjPPEOzuEW3NfLWIJVhKz5l9AxP0G',
                'status'     => '1',
                'country'    => 'Nepal',
                'created_at' => '2016-08-11'
            ],
            [
                'id'         => '71',
                'username'   => 'sagarmatha',
                'first_name' => 'Anup',
                'last_name'  => 'Laudari',
                'email'      => 'anup.laudari@smb.com.np',
                'company'    => 'Sagarmatha Finance Ltd.',
                'address'    => 'Manbhawan ',
                'phone'      => '5547841,5535158',
                'password'   => '$2y$10$3QvdNsHkYmjHh3aRmhMSKu4kJRhG.Y1G.CoNSr3NulbA8y6pPQx4e',
                'status'     => '1',
                'country'    => 'Nepal',
                'created_at' => '2016-08-12'
            ],
            [
                'id'         => '72',
                'username'   => 'gyanodaya',
                'first_name' => 'Ghanashyam',
                'last_name'  => 'Joshi',
                'email'      => 'lovelyneo123@gmail.com',
                'company'    => 'Gyanodaya Residential School',
                'address'    => 'Khokana',
                'phone'      => '9848755636',
                'password'   => '$2y$10$oIGIXLczde0yvjNYYEdv3.qTiH19LNAIHntYyuZeOgHoj6O59kuWe',
                'status'     => '0',
                'country'    => 'Nepal',
                'created_at' => '2016-08-14'
            ],
            [
                'id'         => '73',
                'username'   => 'olympia',
                'first_name' => 'Samir',
                'last_name'  => 'Maharjan',
                'email'      => 'admission@olympia.edu.np',
                'company'    => 'Olympia World School',
                'address'    => 'Babarmahal',
                'phone'      => '',
                'password'   => '$2y$10$oIGIXLczde0yvjNYYEdv3.qTiH19LNAIHntYyuZeOgHoj6O59kuWe',
                'status'     => '0',
                'country'    => 'Nepal',
                'created_at' => '2016-08-14'
            ],
            [
                'id'         => '74',
                'username'   => 'traveldoor',
                'first_name' => 'Gopal',
                'last_name'  => 'P. Kharel',
                'email'      => 'info@traveldoornepal.com',
                'company'    => 'Travel Door Nepal',
                'address'    => 'Thamel',
                'phone'      => '9802006846,9851106346',
                'password'   => '$2y$10$oIGIXLczde0yvjNYYEdv3.qTiH19LNAIHntYyuZeOgHoj6O59kuWe',
                'status'     => '0',
                'country'    => 'Nepal',
                'created_at' => '2016-08-17'
            ],
            [
                'id'         => '75',
                'username'   => 'froxjob',
                'first_name' => 'Bimal',
                'last_name'  => 'Kandel',
                'email'      => 'bimal@froxjob.com',
                'company'    => 'Frox Job',
                'address'    => 'Anamnagar',
                'phone'      => '4244727,9851148454',
                'password'   => '$2y$10$oIGIXLczde0yvjNYYEdv3.qTiH19LNAIHntYyuZeOgHoj6O59kuWe',
                'status'     => '0',
                'country'    => 'Nepal',
                'created_at' => '2016-08-21'
            ],
            [
                'id'         => '76',
                'username'   => 'bikram',
                'first_name' => 'Bikram',
                'last_name'  => 'Shrestha',
                'email'      => 'bikram.shrestha@idea.com.np',
                'company'    => 'Honeynet Project',
                'address'    => 'Kathmandu',
                'phone'      => '9851000044',
                'password'   => '$2y$10$oIGIXLczde0yvjNYYEdv3.qTiH19LNAIHntYyuZeOgHoj6O59kuWe',
                'status'     => '0',
                'country'    => 'Nepal',
                'created_at' => '2016-08-22'
            ],
            [
                'id'         => '77',
                'username'   => 'prabal',
                'first_name' => 'Prabal',
                'last_name'  => 'Man Singh Gurung',
                'email'      => 'gurungprabal@hotmail.com',
                'company'    => 'The Maroons Trading',
                'address'    => 'Naxal',
                'phone'      => '9851144910',
                'password'   => '$2y$10$IPFo48lPTBsMUtWBwyG.N.AXFMEuOdFxqxIJ48Nrs7u4iCeHgTMNG',
                'status'     => '1',
                'country'    => 'Nepal',
                'created_at' => '2016-08-26'
            ],
            [
                'id'         => '78',
                'username'   => 'luitelbj',
                'first_name' => 'Bijay',
                'last_name'  => 'Luitel',
                'email'      => 'luitelbj@gmail.com',
                'company'    => 'Haze Soft Pvt. Ltd.',
                'address'    => 'Baneshwor',
                'phone'      => '9842287342',
                'password'   => '$2y$10$Fs3fs8zovaZCTO9RQiXrZuyaBHJs35VsXvWIT/4xhG2i/0D5lwcJu',
                'status'     => '1',
                'country'    => 'Nepal',
                'created_at' => '2016-08-26'
            ],
            [
                'id'         => '79',
                'username'   => 'hari',
                'first_name' => 'Hari',
                'last_name'  => 'Narayan Yadav',
                'email'      => 'yadav_hn@hotmail.com',
                'company'    => 'Nasa International College',
                'address'    => 'Tinkune ',
                'phone'      => '9851083679',
                'password'   => '$2y$10$GKoMdZoaKvc3iq5JG.kg/Ol4lNQolIbb.s6ybn5py8/78O1lSAIsS',
                'status'     => '1',
                'country'    => 'Nepal',
                'created_at' => '2016-08-28'
            ],
            [
                'id'         => '80',
                'username'   => 'curvesncolors',
                'first_name' => 'Ranjan',
                'last_name'  => 'Shrestha',
                'email'      => 'ranjan@curvesncolors.com',
                'company'    => 'Curves N\' Colors',
                'address'    => 'Kamladi',
                'phone'      => '4249042,9851042407',
                'password'   => '$2y$10$oIGIXLczde0yvjNYYEdv3.qTiH19LNAIHntYyuZeOgHoj6O59kuWe',
                'status'     => '0',
                'country'    => 'Nepal',
                'created_at' => '2016-08-29'
            ],
            [
                'id'         => '81',
                'username'   => 'cert',
                'first_name' => 'Kishan',
                'last_name'  => 'Panday',
                'email'      => 'kishan.panday@cert.com.np',
                'company'    => 'Nepal Certifying Company',
                'address'    => 'Kathmandu',
                'phone'      => '',
                'password'   => '$2y$10$oIGIXLczde0yvjNYYEdv3.qTiH19LNAIHntYyuZeOgHoj6O59kuWe',
                'status'     => '0',
                'country'    => 'Nepal',
                'created_at' => '2016-08-30'
            ],
            [
                'id'         => '82',
                'username'   => 'ibadal',
                'first_name' => 'Indiver',
                'last_name'  => 'Badal',
                'email'      => 'ib@indiver.com',
                'company'    => 'Indiver',
                'address'    => 'Kathmandu',
                'phone'      => '9801044533',
                'password'   => 'e7155b0852e08c88a06c3f0dfe120336',
                'status'     => '0',
                'country'    => 'Nepal',
                'created_at' => '2016-04-20'
            ],
            [
                'id'         => '83',
                'username'   => 'ambika',
                'first_name' => 'Ambika',
                'last_name'  => 'Osti',
                'email'      => 'ambika.osti@gmail.com',
                'company'    => 'Nalibeli',
                'address'    => 'Kathmandu',
                'phone'      => '4422804',
                'password'   => '$2y$10$oIGIXLczde0yvjNYYEdv3.qTiH19LNAIHntYyuZeOgHoj6O59kuWe',
                'status'     => '0',
                'country'    => 'Nepal',
                'created_at' => '2016-09-05'
            ],
            [
                'id'         => '84',
                'username'   => 'dipeshan',
                'first_name' => 'Dipeshan',
                'last_name'  => 'Kshetri',
                'email'      => 'dipeshan.k@gmail.com',
                'company'    => 'Idea Fusion Lab',
                'address'    => 'Gongabu',
                'phone'      => '9801164703',
                'password'   => '$2y$10$4GcKJNyuk/ORaEtXnPcZ7u8Ch8IjZBOKvF7G5XMVTS4fZNPZZRZ0C',
                'status'     => '1',
                'country'    => 'Nepal',
                'created_at' => '2016-08-23'
            ],
            [
                'id'         => '85',
                'username'   => 'mani',
                'first_name' => 'Mani',
                'last_name'  => 'Manandhar',
                'email'      => 'mani@reliancenepal.com.np',
                'company'    => 'Reliance Lotus fincance',
                'address'    => '',
                'phone'      => '9851188320',
                'password'   => '$2y$10$od5Pn/epBfYK5XqvWKY81uFePCwxsK1J8QMkCXcMCZwVMcgsARIDO',
                'status'     => '1',
                'country'    => 'Nepal',
                'created_at' => '2016-09-05'
            ],
            [ 'id'         => '86',
              'username'   => 'pradeep',
              'first_name' => 'Pradeep',
              'last_name'  => 'Mondal',
              'email'      => 'pradeep.modal@cncnepal.com',
              'company'    => 'CNC Pvt. Ltd.',
              'address'    => 'Thirbum Sadak, Dillibazar',
              'phone'      => '4416530,4445997,9851035839',
              'password'   => '$2y$10$oIGIXLczde0yvjNYYEdv3.qTiH19LNAIHntYyuZeOgHoj6O59kuWe',
              'status'     => '0',
              'country'    => 'Nepal',
              'created_at' => '2016-09-07'
            ]
        ];

        DB::statement('SET FOREIGN_KEY_CHECKS=0;');
        DB::table('customers')->truncate();
        DB::table('customers')->insert($customers);
        DB::statement('SET FOREIGN_KEY_CHECKS=1;');
    }
}
